<?php
// install.php - Step 1: Database & AbuseIPDB config

// Ako config već postoji, nema smisla raditi instalaciju
if (file_exists(__DIR__ . '/config.php')) {
    echo "<p>config.php already exists. If you want to rerun the installer, delete config.php first.</p>";
    exit;
}


$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? '');
    $db_pass = trim($_POST['db_pass'] ?? '');
    $abuse_key = trim($_POST['abuseipdb_api_key'] ?? '');

    if ($db_name === '' || $db_user === '') {
        $error = "Database name and user are required.";
    } else {
        // Pokušaj konekcije na bazu
        try {
            $dsn = "mysql:host={$db_host};dbname={$db_name};charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            // Ako konekcija prođe, generiramo config.php
            $configTemplate = <<<PHP
<?php
// Auto-generated by install.php

\$DB_HOST = '{$db_host}';
\$DB_NAME = '{$db_name}';
\$DB_USER = '{$db_user}';
\$DB_PASS = '{$db_pass}';

try {
    \$dsn = "mysql:host={\$DB_HOST};dbname={\$DB_NAME};charset=utf8mb4";
    \$pdo = new PDO(\$dsn, \$DB_USER, \$DB_PASS, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
} catch (PDOException \$e) {
    die("Database connection failed: " . \$e->getMessage());
}

// AbuseIPDB API key (optional)
\$ABUSEIPDB_API_KEY = '{$abuse_key}';

// Flag that basic config exists
define('APP_CONFIGURED', true);
PHP;

            file_put_contents(__DIR__ . '/config.php', $configTemplate);

            $success = "Configuration saved. You can proceed to the next step.";
            // kasnije ćemo dodati redirect na step2, npr. install-db.php
            header("Refresh: 1; URL=install-db.php");
            exit;
        } catch (PDOException $e) {
            $error = "Database connection failed: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Web Monitor - Installation</title>
    <link rel="stylesheet" href="public/css/app.css">
    <style>
        body {
            background-color: #f4f6f9;
        }

        .install-wrapper {
            max-width: 560px;
            margin: 60px auto;
            background: #fff;
            border-radius: 12px;
            padding: 24px 28px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
        }

        .install-title {
            margin-bottom: 10px;
        }

        .install-subtitle {
            margin-bottom: 20px;
            color: #666;
        }

        .form-text {
            font-size: 0.85rem;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="install-wrapper">
        <h1 class="install-title">Web Monitor – Installation</h1>
        <p class="install-subtitle">
            Step 1: Database connection & AbuseIPDB configuration.
        </p>

        <p>
            Before you start, create an empty MySQL database and a user with permissions
            to create tables (CREATE, ALTER, INSERT, UPDATE, DELETE).
        </p>

        <ol>
            <li>Log in to your hosting control panel (cPanel, Plesk, etc.)</li>
            <li>Create a new MySQL database</li>
            <li>Create a MySQL user and assign it to the database</li>
            <li>Remember the host, database name, username and password</li>
        </ol>

        <?php if ($error): ?>
            <div class="alert alert-danger mt-3"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>

        <?php if ($success): ?>
            <div class="alert alert-success mt-3"><?= htmlspecialchars($success) ?></div>
        <?php endif; ?>

        <form method="post" class="mt-3">
            <div class="mb-3">
                <label class="form-label">Database host</label>
                <input type="text" name="db_host" class="form-control"
                    value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>">
                <div class="form-text">Usually <code>localhost</code> or a host provided by your provider.</div>
            </div>

            <div class="mb-3">
                <label class="form-label">Database name</label>
                <input type="text" name="db_name" class="form-control" required
                    value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>">
            </div>

            <div class="mb-3">
                <label class="form-label">Database user</label>
                <input type="text" name="db_user" class="form-control" required
                    value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>">
            </div>

            <div class="mb-3">
                <label class="form-label">Database password</label>
                <input type="password" name="db_pass" class="form-control"
                    value="<?= htmlspecialchars($_POST['db_pass'] ?? '') ?>">
            </div>

            <hr>

            <div class="mb-3">
                <label class="form-label">AbuseIPDB API Key (optional)</label>
                <input type="text" name="abuseipdb_api_key" class="form-control"
                    value="<?= htmlspecialchars($_POST['abuseipdb_api_key'] ?? '') ?>">
                <div class="form-text">
                    Register at <a href="https://www.abuseipdb.com/register" target="_blank">abuseipdb.com</a>
                    and copy your API key. If you leave this empty, IP reputation checks will be disabled.
                </div>
            </div>

            <button type="submit" class="btn btn-primary">
                Save configuration & continue
            </button>
        </form>

    </div>
</body>

</html>